import turtle
from turtle import *

from init import init


def draw_tree():
    pencolor("green")
    pensize(10)
    penup()
    hideturtle()
    goto(200, 150)
    showturtle()
    pendown()
    shape(name="classic")
    seth(-120)
    for i in range(10):
        fd(12)
        # right(2)
    penup()
    goto(200, 150)
    seth(-60)
    pendown()
    for i in range(10):
        fd(12)
        # left(2)
    seth(-150)
    penup()
    fd(10)
    pendown()
    pencolor("gold")
    fd(50)
    seth(-150)
    penup()
    fd(8)
    pendown()
    fd(50)
    seth(-155)
    penup()
    fd(5)
    pendown()
    fd(35)
    # 画第二层
    pencolor("green")
    penup()
    goto(145, 34)
    pendown()
    seth(-120)
    fd(80)
    penup()
    goto(250, 35)
    seth(-60)
    pendown()
    fd(80)
    seth(-150)
    penup()
    fd(10)
    seth(-155)
    pendown()
    pencolor("red")
    fd(50)
    penup()
    fd(10)
    seth(-155)
    pendown()
    fd(60)
    penup()
    fd(8)
    seth(-155)
    pendown()
    fd(50)
    penup()
    seth(-155)
    fd(8)
    pendown()
    fd(55)

    # 画第三层
    penup()
    goto(100, -40)
    seth(-120)
    pendown()
    pencolor("green")
    for i in range(10):
        fd(6)
        right(3)
    penup()
    goto(280, -39)
    seth(-50)
    pendown()
    for i in range(10):
        fd(6)
        left(3)
    seth(-155)
    penup()
    fd(10)
    pendown()
    for i in range(5):
        fd(8)
        right(10)
    penup()
    fd(8)
    seth(-145)
    pendown()
    for i in range(7):
        fd(8)
        right(10)
    penup()
    fd(8)
    seth(-145)
    pendown()
    for i in range(7):
        fd(7)
        right(10)
    penup()
    fd(8)
    seth(-145)
    pendown()
    for i in range(7):
        fd(7)
        right(10)
    penup()
    fd(8)
    seth(-140)
    pendown()
    for i in range(7):
        fd(6)
        right(10)

    # 画第四层
    penup()
    goto(80, -95)
    seth(-130)
    pendown()
    for i in range(7):
        fd(10)
        right(5)
    penup()
    goto(300, -95)
    seth(-50)
    pendown()
    for i in range(7):
        fd(10)
        left(5)
    penup()
    seth(-120)
    fd(10)
    seth(-155)
    pendown()
    for i in range(6):
        fd(8)
        right(10)
    penup()
    seth(-160)
    fd(10)
    seth(-155)
    pendown()
    for i in range(6):
        fd(8)
        right(10)
    penup()
    seth(-160)
    fd(10)
    seth(-155)
    pendown()
    for i in range(6):
        fd(8)
        right(10)
    penup()
    seth(-160)
    fd(10)
    seth(-160)
    pendown()
    for i in range(6):
        fd(8)
        right(10)
    penup()
    seth(-160)
    fd(10)
    seth(-160)
    pendown()
    for i in range(6):
        fd(8)
        right(10)
    penup()
    seth(-160)
    fd(10)
    seth(-165)
    pendown()
    for i in range(5):
        fd(10)
        right(11)
    # 画树干
    pencolor("#8B8386")
    penup()
    goto(150, -165)
    seth(-85)
    pendown()
    fd(75)
    penup()
    goto(250, -165)
    seth(-95)
    pendown()
    fd(75)
    seth(-170)
    penup()
    fd(10)
    pendown()
    pendown()
    for i in range(10):
        fd(7)
        right(2)


if __name__ == '__main__':
    init()
    draw_tree()
    turtle.done()
